### Working with Numpy - for mathematical operations

In [1]:
import numpy as np

In [3]:
a = np.array([1,2 ,3, 4, 5])
print(a)
print(type(a))

print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
b = np.array([[1], [2], [3], [4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [7]:
print(b[0][0])

1


In [12]:
a = np.array([[1,2], [3, 5]])
print(a)
print(a.shape)
print(a[1][0])

[[1 2]
 [3 5]]
(2, 2)
3


# create zeroes, ones, custom array

In [22]:
a = np.zeros((3,3))
print(a)

b = np.ones((2, 3))
print(b)

# array of some constants
c = np.full((3, 2), 5)
print(c)

# Identitiy Matric - Size/Square matrix
d = np.eye(4)
print(d)

#Random Matrix
randomMatrix = np.random.random((2, 3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.53922038 0.49732587 0.35394272]
 [0.26138518 0.93857675 0.58393098]]


In [26]:
print(randomMatrix[:, 2])

[0.35394272 0.58393098]


In [28]:
randomMatrix[1, 1:3] = 1
print(randomMatrix)

[[0.53922038 0.49732587 0.35394272]
 [0.26138518 1.         1.        ]]


In [35]:
z = np.zeros((3, 2), dtype = np.int64)
print(z)

z[1, :] = 5
z[ :, -1] = 7

print(z)

[[0 0]
 [0 0]
 [0 0]]
[[0 7]
 [5 7]
 [0 7]]


In [37]:
# Datatypes
print(z.dtype)

int64


In [45]:
# Mathematical Operations

x = np.array([[1, 2], [3, 4]])
y = np.array([[5,6 ], [7, 8]])

#Element Wise Addition
print(x+y)
print(x-y)
print(np.divide(x, y))
print(np.sqrt(x))
print(x/y)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [48]:
# Matrix Multiplication/ Dot Product

print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [52]:
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [54]:
# Multiplication(Dot Product) of vectors => Scalar
a = np.array([1,2,3, 4])
b = np.array([1, 2,3, 4])
print(a.dot(b))

30


In [56]:
print(a)

[1 2 3 4]


In [58]:
print(sum(a))

10


In [60]:
print(np.sum(a))

10


In [62]:
print(x)

[[1 2]
 [3 4]]


In [65]:
print(np.sum(x))
print(np.sum(x, axis = 0)) # coloumns
print(np.sum(x, axis = 1)) # rows

10
[4 6]
[3 7]


In [67]:
# stacking of arrays
print(a)
b = b**2
print(b)

[1 2 3 4]
[  1  16  81 256]


In [79]:
a = np.stack((a, b),axis=0)
# np.stack((a, b),axis=1)

In [82]:
# reshaoe a numpy array
# print(a)
a = a.reshape((4, 2))
print(a)

[[  1   2]
 [  3   4]
 [  1  16]
 [ 81 256]]


In [88]:
a = a.reshape((2, -1))
print(a)

[[  1   2   3   4]
 [  1  16  81 256]]


# Numpy Random Module
- rand: Random in a given shape.
- randn: Return a sample(or samples) from the "standard normal" distribution.
- randint: Return random integers from low(inclusive) to high(exclusive)
- random: Return random floats in the half-open interval[0.0, 1.0)
- choice: Generates a random sample from a given 1-D array
- Shuffle: Shuffles the contents of sequence

In [91]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [93]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [137]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[8 5 8]


In [100]:
a = np.random.rand(2, 3)
print(a)

[[0.85388753 0.84655027 0.50964604]
 [0.63692858 0.03938181 0.13368946]]


In [102]:
a = np.random.randn(2, 3)
print(a)

[[-1.94407176 -2.67264637 -0.34676567]
 [ 1.27123563 -0.18810074  0.26422225]]


In [110]:
a = np.random.randint(5, 10, 3)
print(a)

[8 8 5]


In [135]:
# randomly pick one element from a array
element = np.random.choice([1, 4, 3, 2, 11, 27])
print(element)

1


# Some more Numpy Functions - Statistics
- min, max
- mean
- median
- average
- variance
- standard deviation


In [143]:
a = np.array([[1, 2, 3, 4], [7, 6, 2, 0]])
print(a)
print(np.min(a))
# Specify axis for the direction in case of multidim array
print(np.min(a, axis =0 ))


# Mean, average all the elements

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]


In [149]:
b = np.array([1, 2, 3, 4 ,5])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a, axis = 0))
print(np.mean(a, axis = 1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [157]:
c = np.array([1, 5, 4, 2, 0])

print(np.median(c))

# Mean vs Average is Weighted
print(np.mean(c))


# Weights
w = np.array([1, 2, 3, 4,5])
# w = np.array([1, 1, 1,1 ,1])
print(np.average(c, weights =w))

# Standard Deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

#inbuilt Function
dev = np.std(c)
print(dev)

#Variance
print(myStd**2)
print(np.var(c))

2.0
2.4
2.066666666666667
1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004
